---

DIVISION: CAC

DEPLOY_SCRIPT: peppermint-sparkles/ci/scripts/push.sh

PCF_API: https://api.sys.cac.preview.pcf.manulife.com
PCF_HELPER_API: https://enterprise-pipeline-node.apps.cac.preview.pcf.manulife.com/fly

PCF_DEV_USER: concourse-dev
PCF_DEV_PASS: "!6VBrw,%"

PCF_TST_USER: concourse-dev
PCF_TST_PASS: "!6VBrw,%"

PCF_UAT_USER: gsdpcfconcourseuatld
PCF_UAT_PASS: ""

PCF_PROD_USER: gsdpcfconcourseprodl
PCF_PROD_PASS: ""

ARTIFACTORY_URI: https://10.234.24.10/artifactory
ARTIFACTORY_USER: user
ARTIFACTORY_PASS: APCYXWVLjd5ufKYq
ARTIFACTORY_REPO: /libs-release-local/oa-montreal/peppermint-sparkles/

APP_NAME: peppermint-sparkles 
APP_VERSION: v2.1.1

GIT_URI: ssh://git@git.platform.manulife.io:2222/oa-montreal/peppermint-sparkles.git
GIT_BRANCH: ci

GIT_PRIVATE_KEY: |
  -----BEGIN RSA PRIVATE KEY-----
  MIIJKAIBAAKCAgEA8femxHGdKkCjsGMPlvri64WlgnKBBAD05URA4nHulJwwUdyH
  E9r6u2Ii7zzzi+Zat7/Scf0+77P9LpRkUHBH6q3/O9Ol4QHgmwdRvAWJuAReiHz5
  4ZiMG4FDTOSJt5HGO4ZzogBYAOuyJNUcCnIZa9rupFAY9CphSeZ+2OkhHb/qNVOw
  FDQfRkxwvLz7b9e+CyogzV2zTKJNZ8ahM0X5ZZOOVJTCpII7OWIekyCAsU3Q7FK7
  1T1KI0Xz7xL9fwtaTF8kg6ZpG4kabSHeHGOH5n2K/GrTZNg7/st28nmPZxzXv4Ja
  NM7sJz80mvtk14da31u7UNdgiYWQmxPkX1XE/ko2ZpXY05KN7p7AhxcVa9+k2rJM
  PJgTrxVY7xpZcyFa0xVz360y0Zv6Rj+fr0nAQUSyDdVCQItLxmPi3ZoanIZK7RPr
  SThJO+3dAFihnUqu3a0bWxBFDC0Vq/FrSiXZ6aL3DMnaOM0aiGEi6VkkAcDrDaGK
  /8RN+Hqdw7CMgtZmPIMeTpDuh6512UKnr3xykHG9jadcYfJHBprbFNIZDYD94ey5
  kpyyy4B3C+jQYfEOAzWYsU0U1lkeNdnNgoaccKP6EYyv/CC3mw7d3kNXgFqa/JVi
  OUrTAH7/riN+ET3zGUT3GEV/78UJwaDqjE7YovtK53FsaLpciKW5x57FoacCAwEA
  AQKCAgBeaPWt4nKjQNNdiFlV3JBbuyrICitix4jGR+pVMIUZgROtbTFbQu7f3Dur
  Qwn4BSpSVcsj5N8AoibgXNADPrwgykEzM7KeZ6AefS2cAkEpBrNn5/OL3XyVYstC
  nk1Jzdwd76kAhcfQnCZHDsvBG6HlnmfMvt/trPeG4SOPOO9N70rQAdZLG8c0I7E9
  QzOMAQ7KxmZEGxJRjWZMXokZO21C/97iC6UikRnQmwM4/s6X37fr7aASZLafqrSy
  DKPSRTi3Ycwaffy23Ljt6fAC/abR/RwUvw26ZFCMaxD/LQUSA4P+2jqeLjqgWZ4J
  9przKYIAcodU1KR7JB03FPzfYdTZbRrUZbZJqo+M1tB1G3riwBcoIOrTOg63ZyZd
  D9Z5bcqOfLEchDX+q0gp7961986218xYlVpzvFjTwApDDBsXousRDksPpyQ83mHy
  kz+8D4d3oFHu22ZtfW/ZiLBxb/mp1MnhuQ2O9TtcdpY4HX8cecYeeWfTwAYL9WDJ
  6RBcrftrzGrq9tSjQ7MCD885tJ57NzkxLWaZKYX+XVpZksc/T/uUtAtoMcElXdrU
  x4QGIuMKOmfFjWu6m5V2KR3T+brrAhHbO2iAaU7fdngd0XpkUyChaea9Y3ilima6
  EX/e27csu5ddNAty4XIMD3QOTs/bNBmtPsqEpDZ8fY0I1Y/+2QKCAQEA+yJXhj0u
  duEh8TZ4jtoJ25upnO+8PgBzN3Q8jLsSR0VBedp1WmP2f6sRO7SudzL2O0UAzmZ/
  JbkEDB5MQUAMlzOMSMiZczP1etoUvvkU1qJkZ3lJm5P+DNf6rZm3ENqVco0ebfG3
  p98yJnZLdwPI/NU6k4WvOvoqVANemrhFZbAlwj0crR3SS/Ef0qL6EKP08LPsRwtA
  fQBHSXN+RMycyLlo66adMX84B2aT5iLZACVcA4xUbRlwtQ4+s4h5+TqnFR3gSUsj
  34bU2jTTCU+bYVkyrXhneRKJZY/Wnlt7ta2HGrk2bkL4aQj8NEYQrmbJs2rJeJ4s
  GFaoSCKqtae9CwKCAQEA9qfXWjnFMisWrZYcd/QergJm36ak2CiVXAdQh7d0Pb9O
  63a5VGosTL72JMx68hSwowSg96adRyIXLiaMQfTYNznbf7gJTJuTxUlUm3J/q7Tc
  6DEO8xyrDhjXSugrOu3pO8JvrRjt4XY6Afu1lT8bZNJGgqPNdZ34LyUzAABpoHwB
  Wc5FBisMx8zrJU0Gg7jnjZuXeqYkMKMVQwqNrjzaC/u+UQN1bqHHmhmK8D0rznKw
  NhU2lvJL43k3m1KHHCy/96FSnk9AiOD/BEJ8G83zZRHPFiJZypA13//HvWtiDFIu
  RjFCi9YSB9kw+KFC++BsggrkXzlYBtDb/YGVrnO3VQKCAQANx5id2QWPqFLAdYiv
  7e7UifoIjm75x/SKempIHoumNXqeQQpnZ0zDPJO5fvSDvdwc7HBa4uzfGQPL1m3A
  ts76DO4JoFgrJhK2Jvk0cV5fWJHBy7nqO3iZI9CxbdnJpvTEUFH3HmhBYdHSonMJ
  mL+Sf/Cy34b56XghG/445xuHtN6dhdTo+tXrLNPeLushtp1eB8FTNJ7ZPQasVRX8
  mG2R5fqH06CUcrKUVWCQJCFcDLC70Rtg0SCKDroKB9cJgdphIj6IRwM05KURRAzA
  WgngkZBiTFUBI68+T2IrVkG3ekoLgVYnPq16te+AvsdzilhO6/EaGTO6MicRrjVH
  umh5AoIBAQCd8JmQN7/SwQ6TdrSiBtqCWB1hhsa1dz80n6ZsUQeI5nB1jB9eM2JM
  flcE9z6etqrop/UevzykqOqo7ZwQO+Ubb9viq4ig2lpEERGxPB8OZxCxSYCmIaxS
  qYtqdsH/yQn47yctcvIX1emNDY2XlMJIy/DEhHjyoIWkQrCmhp0cW2tOAyvlqDlV
  0xybVPgf7o2u+nuD2NEBp9vcgux4LpT86WVTYOCYR9WVElgKP1FGr9+vseOzwlDf
  xuXZen3zh6Agw9cwcdUEEPaa1qu77iO1izLMnJBcif1FgvZ2j0VIWHMzFSXkft4q
  0mNuQWyv9mPk3W6gnwqDysejS4/6FjTFAoIBAGDdA7ATJCXdSebHvtO4uD9UFRuo
  86Tjdj0S0jMwihz+Mj8isK6cDT7qeZsqzZWEJiOlGeHRDRug2L/za0yJ6i0d9ANZ
  4+9JXic7zt9XfR1FI1pmfRgCHiArwg33cVK9s8wv0l4KHDHOU6m8D3qcQWWfvmNN
  yAkb4ch/Y977Wcd6Ui/3bqrVt90wjglLBlroYCZfvuRHsDoIC27UQkquftFgvnOZ
  VFT+NtOEjMsYHtDBhFkmKaU+5kglMY4bRoXDRwGQbztmW1+z1xRBtxEJZrwkBT0N
  Txa9OqgywlPDUpajM/7NFgPA9OwBkQrRI1SQkJ7Wu+E0+/gedapKCo8yUFo=
  -----END RSA PRIVATE KEY-----

